apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vehicle-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/stip324/aws-eks-ai-platform.git
    targetRevision: main
    path: helm/vehicle-api

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vehicle-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true